name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: .htaccess
      run: |
        echo "RewriteEngine On" > .htaccess
        echo "RewriteRule ^ index.php [L]" >> .htaccess
    - name: Build Docker image
      run: |
        docker build -t my-php-apache ./tests

    - name: Start Apache
      run: |
        docker run -d --name apache -p 80:80 --network host -v ${{ github.workspace }}:/var/www/html my-php-apache

    - name: Display Apache2 Config
      run: |
        docker exec apache cat /etc/apache2/apache2.conf

    - name: Wait for MySQL
      run: |
        until mysqladmin ping --host=127.0.0.1 --port=3306 --user=root --password=root --silent; do
          echo "Waiting for database connection..."
          sleep 1
        done
    - name: echo env
      run: |
        pwd
        ls -la
        ls -la v1
        ls -la tests

    - name: Wait for Apache
      run: |
        until curl -s http://localhost; do
          echo "Waiting for Apache server..."
          sleep 5
        done

    - name: Curl index.php
      run: |
        curl http://localhost/v1
        curl http://localhost/v1/hoge

