name: nginx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t my-nginx:latest -f nginx/Dockerfile nginx

    - name: Start Nginx
      run: |
        docker run -d \
          --name my-nginx \
          -p 80:80 \
          --network host \
          -v ${{ github.workspace }}/v1:/var/www/html/v1 \
          my-nginx:latest
          # --link mysql:mysql \
          # --link php-fpm:php-fpm \
          # --link mysql:mysql \

    - name: echo env
      run: |
        pwd
        ls -la
        ls -la v1
        ls -la tests

    - name: List running containers
      run: docker ps -a
    - name: Display nginx logs
      run: docker logs --details my-nginx
    - name: Check container status
      run: docker inspect my-nginx

    - name: Test connection
      run: |
        sleep 5 # Wait for nginx to fully start
        curl -f http://localhost/hoge

