name: nginx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run nginx container
      run: |
        docker build -t my-nginx:latest -f nginx/Dockerfile nginx
        docker run -d -p 80:80 \
          --name my-nginx \
          -v ${{ github.workspace }}/v1:/var/www/html/v1 \
          my-nginx:latest

    - name: echo env
      run: |
        pwd
        ls -la
        ls -la v1
        ls -la tests
    - name: List running containers
      run: docker ps -a
    - name: Check container status
      run: docker inspect my-nginx
    - name: Display nginx logs
      run: docker logs my-nginx
    - name: Wait for MySQL to be healthy
      run: |
        until docker exec mysql mysqladmin ping --silent; do
          sleep 5
        done

    - name: Test connection
      run: |
        sleep 5 # Wait for nginx to fully start
        curl -f http://localhost/hoge

