name: nginx

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP and Nginx
      run: |
        docker build -t custom-nginx-php ./nginx
        docker run -d --name nginx -p 80:80 -v ${{ github.workspace }}:/usr/share/nginx/html custom-nginx-php
        sleep 5

    - name: List running containers
      run: docker ps -a
    - name: Check container status
      run: docker inspect nginx
    - name: Display nginx logs
      run: docker logs nginx
    - name: Display nginx Config
      run: |
        docker exec nginx ls /etc
        docker exec nginx cat /etc/nginx/nginx.conf

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping --host=127.0.0.1 --port=3306 --user=root --password=root --silent; do
          echo "Waiting for database connection..."
          sleep 1
        done
        echo healthcheck ok

    - name: echo env
      run: |
        pwd
        ls -la
        ls -la v1
        ls -la tests

    - name: Check redirect
      run: |
        curl http://localhost/some/other/page

