name: nginx

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP and Nginx
      run: |
        docker build -t custom-nginx-php ./nginx
        docker run -d --name web -p 80:80 -v ${{ github.workspace }}:/usr/share/nginx/html custom-nginx-php

    - name: Wait for MySQL to be ready
      run: |
        docker-compose exec mysql mysqladmin --wait=30 ping

    - name: Test PHP and MySQL connection
      run: |
        echo "<?php
        try {
            \$pdo = new PDO('mysql:host=localhost;dbname=testdb', 'testuser', 'testpassword');
            echo 'Connection successful';
        } catch (PDOException \$e) {
            echo 'Connection failed: ' . \$e->getMessage();
        }
        ?>" > /usr/share/nginx/html/test.php
        curl http://localhost/test.php

    - name: Check redirect
      run: |
        curl -I http://localhost/some/other/page

